school_mgmt_system/schoolmgmt/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('student.urls')), 
    path('users/', include('users.urls')), 
]

school_mgmt_system/student/urls.py
from django.urls import path
from . import views
from .views import *

urlpatterns = [
    
    path('', views.studentview, name='studentview'),
    path('studentlist/', StudentList.as_view(),name='student-list'),
    path('studcreate/', views.studentcreateview, name='studentcreateview'),
    path('dashboard/', views.dashboardview, name='dashboard'),
    path('attendance/', views.attendanceview, name='attendanceview'),
    path('markattendance/', views.markattendanceview, name='markattendanceview'),
    path('student/create/', StudentCreate.as_view(),name='student-create'),
    path('student/detail/<int:pk>/', StudentDetail.as_view(),name='student-detail'),
    path('student/update/<int:pk>/', UpdateStudent.as_view(),name='student-update'),
    path('student/delete/<int:pk>/', DeleteStudent.as_view(),name='student-delete'),
    path('studentfilter/', views.StudentFilter.as_view(), name='filter-standard-class-bloodgroup'),
    path('student/total/', TotalStudentCounter.as_view(),name='total-counter'),
    path('student/active/', ActiveStudentCounter.as_view(),name='student-counter'),
    
    path('attendancelist/', AttendanceList.as_view(),name='attendance-list'),
    path('attendancefilter/', views.AttendanceFilter.as_view(), name='filter-attendance'),
    path('attendancecreate/', AttendanceCreate.as_view(),name='attendance-create'),
    path('attendanceupdate/<int:pk>/', AttendanceUpdate.as_view(),name='attendance-update'),
    path('attendancedelete/<int:pk>/', AttendanceDelete.as_view(),name='attendance-delete'),
]

school_mgmt_system/users/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views


urlpatterns = [
    
    path('list/', UserList.as_view(),name='user-list'),
    path('create/', UserRegister.as_view(),name='user-register'),
    path('detail/<int:pk>/', UserDetail.as_view(),name='user-detail'),
    path('update/<int:pk>/', UserUpdate.as_view(),name='user-update'),
    path('delete/<int:pk>/', UserDelete.as_view(),name='user-delete'),

    path('loginview/', Loginview.as_view(),name='user_login'),
    path('login/',loginpage, name='loginview'),
    path('signup/',signuppage, name='signupview'),
    path('logout/', Logoutview.as_view(),name='user-logout'),
    # path('changepassword/', ChangePasswordView.as_view(),name='change-password'),

    path('',homepage, name='home_view'),
    path('passwordchange/',PasswordChangeView.as_view(), name='password_change'),

    path('resetpassword/',PasswordReset.as_view(),name="request-password-reset"),

    path("passwordreset/<str:encoded_pk>/<str:token>/",ResetPasswordComplete.as_view(),name="reset-password"),

    #path('accounts/change-password', ChangePasswordView.as_view(), name='register'),
    #path('changepassword/', PasswordChangeView.as_view()),
    #path('changepassword/done/', auth_views.PasswordChangeDoneView.as_view(template_name="passwordchangedone.html"),name='password_change_done'),
    #path('resetpassword/',auth_views.PasswordResetView.as_view(template_name="password_reset.html"),name='password_reset'),  
    #path('resetpassworddone/',auth_views.PasswordResetDoneView.as_view(template_name="password_reset_done.html"),name='password_reset_done'),  
    #path('resetpasswordconfrim/<uidb64>/<token>/',auth_views. PasswordResetConfirmView.as_view(),name='password_reset_confirm'),  
    #path('resetpasswordcomplete/',auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"),name='password_reset_complete'),    
]

school_mgmt_system/student/models.py
from django.db import models

# Create your models here.

RELATIONSHIP_CHOICES= (('Father','Father'),('Mother', 'Mother'),('GrandParent', 'Grand Parent'))  
GENDER_CHOICES= (('Male','Male'),('Female', 'Female')) 
#_CHOICES= (('Male','Male'),('Female', 'Female')) 
STANDARD_CHOICES= (('1','I'),('2','II'),('3','III'),('4','IV'),('5','V'),('6','VI'),('7','VII'),('8','VIII'),('9','IX'),('10','X')) 
DIVISION_CHOICES= (('A','A'),('B','B'),('C','C'),('D','D'),('E','E'))
BLOODGROUP_CHOICES= (('Apositive ','A+'),('Anegative', 'A-'),('Bpositive', 'B+'),('Bnegative', 'B-'),('Opositive', 'O+'),('Onegative', 'O-'),('ABpositive', 'AB+'),('ABnegative', 'AB-'),) 
STATE_CHOICES = (
    ('AndhraPradesh','Andhra Pradesh'),
    ('AndamanandNicobarIslands', 'Andaman and Nicobar Islands'),
    ('Arunachal Pradesh','Arunachal Pradesh'),
    ('Assam','Assam'),
    ('Bihar','Bihar'),
    ('Chandigarh','Chandigarh'),
    ('Chhattisgarh','Chhattisgarh'),
    ('Delhi','Delhi'),
    ('Lakshadweep','Lakshadweep'),
    ('Puducherry','Puducherry'),
    ('Goa','Goa'),
    ('Gujarat','Gujarat'),
    ('Haryana','Haryana'),
    ('HimachalPradesh','Himachal Pradesh'),
    ('JammuandKashmir','Jammu and Kashmir'),
    ('Jharkhand','Jharkhand'),
    ('Karnataka','Karnataka'),
    ('Kerala','Kerala'),
    ('MadhyaPradesh','Madhya Pradesh'),
    ('Maharashtra','Maharashtra'),
    ('Manipur','Manipur'),
    ('Meghalaya','Meghalaya'),
    ('Mizoram','Mizoram'),
    ('Nagaland','Nagaland'),
    ('Odisha','Odisha'),
    ('Punjab','Punjab'),
    ('Rajasthan','Rajasthan'),
    ('Sikkim','Sikkim'),
    ('TamilNadu','Tamil Nadu'),
    ('Telangana','Telangana'),
    ('Tripura','Tripura '),
    ('Uttar Pradesh','Uttar Pradesh'),
    ('Uttarakhand','Uttarakhand'),
    ('West Bengal','West Bengal'),  
)

ACTIVE_CHOICES= (('1','1'),('2', '2')) 

class Student(models.Model):
    student_ID = models.CharField(max_length=40, primary_key=True)
    first_name = models.CharField(max_length=40, null=True, blank=True)
    last_name = models.CharField(max_length=40, null=True, blank=True)
    guardian_name = models.CharField(max_length=40, null=True, blank=True)
    guardian_relationship = models.CharField(choices=RELATIONSHIP_CHOICES,max_length=40, null=True, blank=True)
    guardian_phone = models.IntegerField(null=True, blank=True)
    gender = models.CharField(choices=GENDER_CHOICES,max_length=40, null=True, blank=True)
    email = models.EmailField(max_length=40, null=True, blank=True)
    address = models.TextField(max_length=40, null=True, blank=True)
    pincode = models.IntegerField(null=True, blank=True)
    district = models.CharField(max_length=40, null=True, blank=True)
    state = models.CharField(max_length=40, choices=STATE_CHOICES, default='Kerala')
    standard = models.CharField(choices=STANDARD_CHOICES, max_length=10, null=True, blank=True)
    division = models.CharField(choices=DIVISION_CHOICES,max_length=10,null=True, blank=True)
    date_of_birth = models.DateField(max_length=40, null=True, blank=True)
    blood_group = models.CharField(choices=BLOODGROUP_CHOICES,max_length=40,null=True, blank=True)
    photo = models.ImageField(null=True, blank=True)
    bus_no = models.IntegerField(null=True, blank=True)
    isactive = models.CharField(max_length=10,choices=ACTIVE_CHOICES, default='1')

    def __str__(self):
        return self.first_name


ATTENDANCE_CHOICES= (('Fulldaypresent','P'),('Fulldayabsent', 'A'),('Halfdayleave', 'H'))  

class Attendance(models.Model):
    date = models.DateField(max_length=40, null=True, blank=True)
    markattendance= models.CharField(choices=ATTENDANCE_CHOICES, max_length=40, null=False,default='P')
    student=models.ForeignKey(Student,null=True,blank=True, on_delete=models.CASCADE,related_name='stud_id')
   

school_mgmt_system/student/views.py
from django.shortcuts import render
from rest_framework import generics
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from .models import Student
from .serializers import *
from django_filters.rest_framework import DjangoFilterBackend
from django.views.generic import View
# Create your views here.



#STUDENT MODEL

def studentview(request):
    return render(request, 'studentlist.html')

#RETRIEVE ALL 

class StudentList(APIView):
    
    def get(self, request):
        items = Student.objects.order_by('student_ID')
        serializer = StudentSerializers(items, many =True)
        studentlist=serializer.data
        return Response(studentlist, status=status.HTTP_200_OK)
        #return render(request,  'studentlist.html', {'studentlist':studentlist}, status=status.HTTP_200_OK)
        #return render(request, studentlist, 'studentlist.html')

def studentcreateview(request):
    return render(request, 'regisstud.html')

class StudentCreate(APIView):

    def post(self, request): 
        serializer = StudentSerializers(data=request.data)
        if serializer.is_valid():
            serializer.save()
            items = Student.objects.order_by('student_ID')
            serializers = StudentSerializers(items, many =True)
            student=serializers.data
            return Response(student, status=status.HTTP_200_OK)
        else:
            return Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)
       
#FILTER VIEW   
class StudentFilter(generics.ListAPIView):

    queryset = Student.objects.all()
    serializer_class = StudentSerializers
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['standard', 'division','blood_group']

#DETAIL STUDENT

class StudentDetail(APIView):
  
    def get(self,request, pk):
        student = Student.objects.get(student_ID=pk)
        serializer = StudentSerializers(student, many=False)
        studentdetail=serializer.data
        return Response(studentdetail, status=status.HTTP_200_OK)


#STUDENT UPDATE

class UpdateStudent(APIView):
  
    def get(self,request, pk):
        student = Student.objects.get(student_ID=pk)
        serializer = StudentSerializers(student, many=False)
        studentdetail=serializer.data
        return Response(studentdetail, status=status.HTTP_200_OK)

    def patch(self,request, pk):
        student = Student.objects.get(student_ID=pk)
        serializer = StudentSerializers(instance=student, data=request.data,partial=True)
        if serializer.is_valid():
            serializer.save()
            items = Student.objects.order_by('student_ID')
            serializers = StudentSerializers(items, many =True)
            student=serializers.data
            return Response(student, status=status.HTTP_200_OK)
        else:
            return Response(serializer.errors,status=status.HTTP_304_NOT_MODIFIED)



#DELETE STUDENT

class DeleteStudent(APIView):
  
    def get(self,request,pk):
        user = Student.objects.get(student_ID=pk)
        user.delete()

        items = Student.objects.order_by('student_ID')
        serializer = StudentSerializers(items, many =True)
        student=serializer.data
        return Response(student, status=status.HTTP_200_OK)
      
#ATTENDANCE MODEL

def attendanceview(request):
    return render(request, 'attendance.html')

#LISTVIEW
class AttendanceList(APIView):

    def get(self, request):
        items = Attendance.objects.order_by('date')
        serializer = MarkAttendanceSerializers(items, many =True)
        attendance=serializer.data
        return Response(attendance, status=status.HTTP_200_OK)

#FILTER VIEW   
class AttendanceFilter(generics.ListAPIView):

    queryset = Attendance.objects.all()
    serializer_class = MarkAttendanceSerializers
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['date']

#CREATE VIEW
def markattendanceview(request):
    return render(request, 'markattendance.html')

class AttendanceCreate(APIView):

    def post(self, request): 
        serializer = MarkAttendanceSerializers(data=request.data)
        if serializer.is_valid():
            serializer.save()
            items = Attendance.objects.order_by('date')
            serializers = MarkAttendanceSerializers(items, many =True)
            attendance=serializers.data
            print(attendance)
            return Response(attendance, status=status.HTTP_200_OK)
        else:
            return Response(serializer.errors,status=status.HTTP_304_NOT_MODIFIED)


#ATTENDANCE UPDATE

class AttendanceUpdate(APIView):
  
    def get(self,request, pk):
        item = Attendance.objects.get(id=pk)
        serializer = MarkAttendanceSerializers(item, many=False)
        attendance=serializer.data
        return Response(attendance, status=status.HTTP_200_OK)

    def post(self,request, pk):
        item = Attendance.objects.get(id=pk)
        serializer = MarkAttendanceSerializers(instance=item, data=request.data)
        if serializer.is_valid():
            serializer.save()
            items = Attendance.objects.order_by('date')
            serializers = MarkAttendanceSerializers(items, many =True)
            attendance=serializers.data
            return Response(attendance, status=status.HTTP_200_OK)
        else:
            return Response(serializer.errors,status=status.HTTP_304_NOT_MODIFIED)



#DELETE ATTENDANCE

class AttendanceDelete(APIView):
  
    def get(self,request,pk):
        user = Attendance.objects.get(id=pk)
        user.delete()

        items = Attendance.objects.order_by('date')
        serializer = MarkAttendanceSerializers(items, many =True)
        attendance=serializer.data
        return Response(attendance, status=status.HTTP_200_OK)


##COUNTER

def dashboardview(request):
    return render(request, 'dashboard.html')

class TotalStudentCounter(APIView):
  
    def get(self,request):
        total_count = Student.objects.count()
        return Response(total_count, status=status.HTTP_200_OK)

class ActiveStudentCounter(APIView):
  
    def get(self,request):
        active_count = Student.objects.filter(isactive='1').count()
        return Response(active_count, status=status.HTTP_200_OK)

school_mgmt_system/student/templates/attendance.html
<html>
    <head>
        <style>
            body{
                background: rgb(131, 170, 203);
                background: linear-gradient(90deg, lightblue, white);
            }
    
            .div-1 {
                background-color: #EBEBEB;
            }
            table {
              width: 50%;
            }
            th {
              background: #f1f1f1;
              font-weight: bold;
              text-align: center;
              padding: 6px;
            }
            td {
              background: #f9f9f9;
              text-align: center;
              padding: 6px;
            }
        
            {box-sizing: border-box;}
        
        /* Button used to open the contact form - fixed at the bottom of the page */
        .open-button {
          background-color: #555;
          color: white;
          padding: 16px 20px;
          border: none;
          cursor: pointer;
          opacity: 0.8;
          position: fixed;
          bottom: 23px;
          right: 28px;
          width: 280px;
        }
        
        /* The popup form - hidden by default */
        .form-popup {
          display: none;
          position: fixed;
          bottom: 0;
          right: 12px;
          border: 3px solid #f1f1f1;
          z-index: 9;
        }
        
        /* Add styles to the form container */
        .form-container {
          max-width: 400px;
          padding: 10px;
          background-color: white;
        }
        
        /* Full-width input fields */
        .form-container input[type=text], .form-container input[type=password] {
          width: 100%;
          padding: 5px;
          margin: 5px 0 22px 0;
          border: none;
          background: #f1f1f1;
        }
        
        /* When the inputs get focus, do something */
        .form-container input[type=text]:focus, .form-container input[type=password]:focus {
          background-color: #ddd;
          outline: none;
        }
        
        /* Set a style for the submit/login button */
        .form-container .btn {
          background-color: #04AA6D;
          color: white;
          padding: 16px 20px;
          border: none;
          cursor: pointer;
          width: 100%;
          margin-bottom:10px;
          opacity: 0.8;
        }
        
        /* Add a red background color to the cancel button */
        .form-container .cancel {
          background-color: red;
        }
        
        /* Add some hover effects to buttons */
        .form-container .btn:hover, .open-button:hover {
          opacity: 1;
        }
    
        </style>
        <title>attendance</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <head>
    <body>
        <br> 
        <center> <h1 style="color:red;">STUDENT MANAGEMENT SYSTEM</h1> </center>
        <br>    <!-- Add Button -->
        <p style="text-align:right">
          <button class ='btn btn-primary m-3 p-2 mark'>Mark Attendance </button>
        </p>
        <div class="row">
            <div class="col-sm-4 col-md-4 col-lg-4">
                <h5>Class</h5> 
                <input type="number" id="Cinput" onkeyup="classFunction()" placeholder="Search for class" title="Type in a class">
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <h5>Student ID</h5>
                <input type="text" id="studentidInput" onkeyup="studentidFilter()" placeholder="Search for studentid" title="Type in a division">
            </div> 
            <div class="col-sm-4 col-md-4 col-lg-3">
                <h5>Date</h5>
                <input type="date" id="dateInput" onkeyup="dateFilter()" placeholder="Search for date" title="Type in a date">
            </div>  
        </div>
       <br>
        <div class="row">
            <div class="col-sm-3 col-md-6 col-lg-2 div-1">
                <nav class="nav-pills nav flex-column ">
                  <a class="nav-link" href="http://127.0.0.1:8000/dashboard/">DashBoard</a>
                  <a class="nav-link" href="http://127.0.0.1:8000/">Student</a>
                  <a class="nav-link" href="http://127.0.0.1:8000/attendance">Attendance</a>
                </nav>
            </div>
           
            <div class="col-sm-9 col-md-6 col-lg-10">
                <!-- The Table -->
                <!---->
                <table class="table table-hover" id="attendtable">
                    <thead>
                        <tr>
                            <th scope="col">Sl No.</th>
                            <th scope="col">Student ID</th>
                            <th scope="col">Attendance</th>
                            <th scope="col">Date</th>
                            <th class="text-center" colspan = "2">Actions</th>
    
                        </tr>
                    </thead>
                    <tbody id="tableBody"> </tbody>
                </table>
            </div>
        </div>
    
        
        <!-- The popup form -->
    <div class="form-popup" id="updateForm">
      <form class="form-container">
    
       
        <input type="hidden" id="id_id_attendance" name="ID"/>
    
        <input type="hidden" id="id_ID" name="studentid"/>
    
        <label for="date"><b>Date</b></label>
        <input type="date" id="id_date" name="date"/>
    
        <label for="markattendance"><b>Mark Attendance</b></label> <br>
        <input type="text" id="id_markattendance" name="markattendance"/>

    
        <button type="submit" class="btn">Update</button>
        <button type="button" class="btn cancel" onclick="closeupdateForm()">Close</button>
      </form>
    </div>  
    <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>  
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"></script>
	  <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script>

    //ADD
    $('.mark').click(function(){
          console.log("add button clicked");
            window.location.href='http://127.0.0.1:8000/markattendance/';
    }) 

    //TABLE AJAX CALL
		$(document).ready(function() {
			$.ajax({
				url: 'http://127.0.0.1:8000/attendancelist/',
				type: 'GET',
				success: function (response) {
					tableDataDisplay(response);	           
				}
			});  
	  })
		

		//TABLE DISPLAY
		function tableDataDisplay(response) {
			
			var tableData = "";
			for (var i=0; i<response.length; i++) {
                console.log(response[i])
                var update_id=response[i].id;
                var delete_id=response[i].id;
                console.log(update_id)
                tableData+= '<tr>';      
                tableData+= '<td>'+ [i+1] + '</td>';                                                          
                tableData+= '<td>'+response[i].student+ '</td>';
                tableData+= '<td>'+response[i].markattendance + '</td>';
                tableData+= '<td>'+response[i].date + '</td>';
                tableData+= '<td> <input class= "btn btn-warning" type="button" value="Update" id="'+update_id+'" onclick="updateattendance(id)"/> </td>';
                tableData+= '<td> <input class= "btn btn-danger" type="button" value="Delete" id="'+delete_id+'" onclick="deleteattendance(id)"/> </td>';
                tableData+= '</tr>';
                }
			document.getElementById("tableBody").innerHTML=tableData;
		    }

        //FILTER
        function classFunction() {
            var input, filter, table, tr, td, i, txtValue;
            input = document.getElementById("Cinput");
            filter = input.value.toUpperCase();
            table = document.getElementById("attendtable");
            tr = table.getElementsByTagName("tr");
            for (i = 0; i < tr.length; i++) {
              td = tr[i].getElementsByTagName("td")[4];
              if (td) {
                txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                  tr[i].style.display = "";
                } else {
                  tr[i].style.display = "none";
                }
              }       
            }
          }

        function studentidFilter() {
            var input, filter, table, tr, td, i, txtValue;
            input = document.getElementById("studentidInput");
            filter = input.value.toUpperCase();
            table = document.getElementById("attendtable");
            tr = table.getElementsByTagName("tr");
            for (i = 0; i < tr.length; i++) {
              td = tr[i].getElementsByTagName("td")[1];
              if (td) {
                txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                  tr[i].style.display = "";
                } else {
                  tr[i].style.display = "none";
                }
              }       
            }
          }
        
        function dateFilter() {
            var input, filter, table, tr, td, i, txtValue;
            input = document.getElementById("dateInput");
            filter = input.value.toUpperCase();
            table = document.getElementById("attendtable");
            tr = table.getElementsByTagName("tr");
            for (i = 0; i < tr.length; i++) {
              td = tr[i].getElementsByTagName("td")[3];
              if (td) {
                txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                  tr[i].style.display = "";
                } else {
                  tr[i].style.display = "none";
                }
              }       
            }
          }
        

      //DELETE FUNCTION
      function deleteattendance(id) {

        var confirmation = confirm("Are you sure you want to delete?");
        if (confirmation) {
          console.log("delete button clicked");
          //console.log(id);
          $.ajax({
             url : "http://127.0.0.1:8000/attendancedelete/"+id+'/',
             type : "GET",
              success:function(response){
                  response =  response;
                  tableDataDisplay(response);
                  alert('attendance record deleted successfully.');
             }
             }) 
            }  
          }

      //UPDATE FUNCTION
      function updateattendance(id) {
			
        var confirmation = confirm("Are you sure that you want to update?");
        if (confirmation){
          console.log("update button clicked");
          console.log(id);
          $.ajax({
            url : "http://127.0.0.1:8000/attendanceupdate/"+id+'/',
            type : "GET",
            success:function(response){
                response =  response;
                //console.log(response)
                var attendid = response.id;
                var student = response.student;
                var date = response.date;
                var markattendance = response.markattendance;
                openupdateForm(attendid,student,date, markattendance) 
              }
  
            }) 
          }  
        }
  
  
      function openupdateForm(attendid,student,date,markattendance) {
          document.getElementById("updateForm").style.display = "block";
          $('#id_id_attendance').val(attendid);
          $('#id_ID').val(student);
          $('#id_date').val(date);
          $('#id_markattendance').val(markattendance);
          $('.btn').click(function(event){
              event.preventDefault;
              console.log("popup form");
              var get_id_attend = $('#id_id_attendance').val();
              var get_ID = $('#id_ID').val();
              var get_date = $('#id_date').val();
              var get_markattendance = $('#id_markattendance').val();
              updatecall(get_id_attend,get_ID,get_date,get_markattendance);
              })
            }
  
  
      function updatecall(get_id_attend,get_ID,get_date,get_markattendance){
  
          $.ajax({
                  url : "http://127.0.0.1:8000/attendanceupdate/"+ID+'/',
                  type : "POST",
                  data : {
                          id: get_id_attend,
                          student: get_ID,
                          markattendance: get_date,
                          date: get_markattendance, 
                          csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                          },
                  success: function (response) {
                          alert("Updated successfully");
                          tableDataDisplay(response);	           
                          }
             })
      }
      
  
      function closeupdateForm() {
  
          document.getElementById("updateForm").style.display = "none";
          window.location.href = "http://127.0.0.1:8000/attendance/";	
      }
      
  
      </script>
    </body>
</html>

school_mgmt_system/student/templates/popup.html
<!-- The popup form -->
<div class="form-popup" id="myForm">
    <form class="form-container">
  
      <label for="ID"><b>ID</b></label>
      <input type="text" id="id_ID" name="ID"/>
  
      <label for="firstname"><b>First Name</b></label>
      <input type="text" id="id_firstname" name="firstname"/>
  
      <label for="lastname"><b>Last Name</b></label>
      <input type="text" id="id_lastname" name="lastname"/>
  
      <label for="id_standard"><b>Class</b></label>
      <input type="text" id="id_standard" name="standard"/>
  
      <label for="id_division"><b>Division</b></label>
      <input type="text" id="id_division" name="division "/>
  
      <label for="id_bloodgroup"><b>Blood Group</b></label>
      <input type="text" id="id_bloodgroup" name="division "/>
  
      <button type="submit" class="btn">Update</button>
      <button type="button" class="btn cancel" onclick="closeForm()">Close</button>
    </form>
  </div>