calorie_tracker_app/accounts/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from .calviews import *
from .stripe_views import *
from rest_framework_simplejwt import views as jwt_views


urlpatterns = [

    path('token/', jwt_views.TokenObtainPairView.as_view(), name ='token_obtain'),
    path('token/refresh/', jwt_views.TokenRefreshView.as_view(), name ='token_refresh'),
    path('token/verify/', jwt_views.TokenVerifyView.as_view(), name ='token_verify'),

    path('list/', UserList.as_view(),name='user_list'),
    path('create/', UserRegister.as_view(),name='user_register'),
    path('detail/<int:pk>/', UserDetail.as_view(),name='user_detail'),
    path('update/<int:pk>/', UserUpdate.as_view(),name='user_update'),
    path('delete/<int:pk>/', UserDelete.as_view(),name='user_delete'),

    path('login/', LoginView.as_view(),name='user_login'),
    path('logout/', Logoutview.as_view(),name='user_logout'),

    path('changepassword/',PasswordChangeView.as_view(), name='password_change'),
    #path('resetpassword/',PasswordReset.as_view(),name="request_password_reset"),
    path('celeryresetpassword/',PasswordResetbyCelery.as_view(),name="request_password_reset"),
    path('passwordreset/<str:encoded_pk>/<str:token>/',ResetPasswordComplete.as_view(),name="reset-password-url"),

    path('consumed/addquantity/', AddConsumed.as_view(),name='add_food_consumed'),
    path('consumed/delete/<int:pk>/', ConsumeDelete.as_view(),name='delete_consumed'),
    path('consumed/listview/', ConsumeList.as_view(),name='consumed_listview'),
    path('search/<str:email>/', SearchByemail.as_view(),name='user_register'),
    path('consumed/searchbyday/', SearchConsumedByDay.as_view(),name='food consumed based on day'),
    path('consumed/searchbymonth/', SearchConsumedByMonth.as_view(),name='food consumed based on month'),
    path('consumed/searchbyweek/', SearchConsumedByWeek.as_view(),name='food consumed based on week'),
    path('consumed/search/range/', SearchRange.as_view(),name='food consumed based on date range'),

    #excel
    path('exporttoexcel/', Export.as_view(), name='export_excel_date'),
    path('exporttoexcel/week/', ExportWeek.as_view(), name='export_excel_week'),
    path('exporttoexcel/month/', ExportMonth.as_view(), name='export_excel_month'),
    
    #pdf
    
    path('pdf/date/', Convert_pdf_by_date.as_view(), name='date_pdf'), 
    path('pdf/week/', Convert_pdf_by_week.as_view(), name='week_pdf'), 
    path('pdf/month/', Convert_pdf_by_month.as_view(), name='month_pdf'), 


    #charts

    path('weekwisechart/', weekwisechart_mixin.as_view(), name='week_chart'), 
    path('daywisechart/', daywisechart_mixin.as_view(), name='day_chart'), 
    path('monthwisechart/', monthwisechart_mixin.as_view(), name='monthwisechart'),

    #stripe
    path('choose_plan/', PaymentView.as_view(), name='choose_plan'),
    path('payment_success/', PaymentSuccess.as_view(), name='payment_success'),

    #----TEMPLATE URLS----
    path('loginpage/',loginpage, name='loginpage'),
    path('userloginpage/',userloginpage, name='userloginpage'), #not required
    path('home/',homepage, name='homepage'), #homepage of user
    path('signup/',signuppage, name='signup'),
    path('userlist/',userlistpage, name='userlist'),
    path('home/',userhomepage, name='userhome'),
    path('oldcalc/',calculatecaloriepage, name='userhome'),
    path('calc/',calculatecaloriespage, name='userhome'),
    path('sheet/',sheetpage, name='usersheet'),
    path('passwordchange/',passwordchangepage, name='password_changepage'),
    path('changepassworddone/',passwordchangedonepage, name='password_change_donepage'),
    path('passwordreset/',passwordresetpage, name='password_resetpage'),
    path('resetpasswordsent/',passwordresetsentpage, name='password_reset_completepage'),
    path('resetpassworddone/',passwordresetdonepage, name='password_reset_donepage'),
    path('resetpassword/<str:encoded_pk>/<str:token>/',passwordresetcompletepage,name="reset-password"),
    path('resetpasswordcomplete/',passwordresetcompletepage, name='password_reset_completepage'),
    path('chart/',chart, name='chart'),
    path('navbar/',navbar, name='navbar'),
    path('adminhome/',adminhome, name='admin_homepage'), #home page of admin

    path('daywisechartpage/',daywisechartpage, name='daywisechartpage'),
    path('weekwisechartpage/',weekwisechartpage, name='weekwisechartpage'),
    path('monthwisechartpage/',monthwisechartpage, name='monthwisechartpage'),

    path('payment_success_page/', payment_success_page, name='payment_success'),
    path('choose_plan_page/', choose_plan_page, name='choose_plan'),
    path('payment_cancel/', payment_cancel_page, name='payment_cancel_page'),


    
]














 
    
    

 

calorie_tracker_app/calorie_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('food/', include('food.urls')),
    path('payments/', include('products.urls')),
    path('chat/', include('chatapp.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)       
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

calorie_tracker_app/food/urls.py
from django.urls import path
from .views import *



urlpatterns = [
    
    #----category-urls----
    path('category/list/', CategoryList.as_view(),name='Category_list'),
    path('category/create/', CategoryCreate.as_view(),name='Category_create'),
    path('category/detail/<int:pk>/', CategoryDetail.as_view(),name='Category_detail'),
    path('category/update/<int:pk>/', CategoryUpdate.as_view(),name='Category_update'),
    path('category/delete/<int:pk>/', CategoryDelete.as_view(),name='Category_delete'),

    #----food-urls----
    path('list/', FoodList.as_view(),name='Food_list'),
    path('create/', FoodCreate.as_view(),name='Food_create'),
    path('detail/<int:pk>/', FoodDetail.as_view(),name='Food_detail'),
    path('update/<int:pk>/', FoodUpdate.as_view(),name='Food_update'),
    path('delete/<int:pk>/', FoodDelete.as_view(),name='Food_delete'),

    #----filter-urls----
    path('filter/category/', CategoryFilter.as_view(), name='CategoryFilter'),
    path('caloryless/', Caloryless.as_view(), name='CategoryFilter'),
    path('calorygt/', CaloryGt.as_view(), name='CategoryFilter'),
    path('calrange/', CaloryRange.as_view(), name='CategoryFilter'),
    path('searchbyname/', SearchFood.as_view(), name='Search name'),

    #----bulk create-urls----
    path('bulkcreate/', Bulkcreate.as_view(), name='bulkcreate'), 

    #----pdf-urls----
    path('pdf/', Convert_pdf_foodlist.as_view(), name='Convert_pdf_foodlist'),
    path('pdf/category/', Convert_pdf_by_category.as_view(), name='Convert_pdf_foodlist'),
    path('pdf/calorieless/', Convert_pdf_by_calorieless.as_view(), name='Convert_pdf_foodlist'),
    path('pdf/caloriegt/', Convert_pdf_by_caloriegt.as_view(), name='Convert_pdf_foodlist'),
    path('pdf/range/', Convert_pdf_by_calorierange.as_view(), name='Convert_pdf_foodlist'),  

    #----word document----
    path('word-document/', WordDocumentView.as_view(), name='word-document'),

    #----TEMPLATE URLS----
    path('listview/',foodlistpage, name='foodlistpage'),
    path('add/',addfoodpage, name='addfoodpage'),
    path('bulkcreatepage/',bulkcreatepage, name='bulkcreatepage'),

]

calorie_tracker_app/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from food.models import FoodItem



# Create your models here.
class UserManager(BaseUserManager):
    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(email, password, **extra_fields)
    

class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True)
    is_staff = models.BooleanField(default=False)
    premium_member = models.BooleanField(default=False)
    plan = models.CharField(max_length=10, null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.email
    


class ConsumedByUser(models.Model):

    user = models.ForeignKey(User, blank=True,on_delete=models.CASCADE, related_name = 'user_food')
    food = models.ForeignKey(FoodItem,blank=True,on_delete=models.CASCADE, related_name='food_consumed')
    quantity = models.FloatField(null=True, blank=True)
    calories = models.FloatField(null=True, blank=True)
    date = models.DateField(auto_now_add=False, auto_now=False, blank=True)

calorie_tracker_app/accounts/templates/chartwithtwoquantity.html
<!DOCTYPE html>
<html>
<head>
    <title>Bar Chart with Two Quantities</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <canvas id="myChart"></canvas>
    <script>
        var ctx = document.getElementById('myChart').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: ['Category 1', 'Category 2', 'Category 3'],
                datasets: [{
                    label: 'Calories Consumed',
                    data: [10, 15, 20],
                    backgroundColor: 'rgba(255, 99, 132, 0.2)',
                    borderColor: 'rgba(255, 99, 132, 1)',
                    borderWidth: 1
                }, {
                    label: 'Quantity consumed',
                    data: [20, 25, 30],
                    backgroundColor: 'rgba(54, 162, 235, 0.2)',
                    borderColor: 'rgba(54, 162, 235, 1)',
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });
    </script>
</body>i will share
</html>

calorie_tracker_app/accounts/templates/login.html
<! DOCTYPE html>  
<html lang="en" >  
<head>  
    <meta charset="UTF-8">  
    <title> Login Page </title>  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">  

    <style>  
        body {  
            background: linear-gradient(to bottom left, white 70%, lightblue);
            font-family: Roboto, sans-serif;
            }
        h1 {  
            color: blue;  
            padding-bottom: 2rem;  
            font-weight: bold;  
        }  
        a {  
        color: #333;  
        }  
        a:hover {  
        color: #E8D426;  
        text-decoration: none;  
        }  
        .form-control:focus {  
            color: #000;  
            background-color: #fff;  
            border: 2px solid #E8D426;  
            outline: 0;  
            box-shadow: none;  
        }  
        .btn {  
        
        border: #E8D426;  
        }  
        .btn:hover {  
        background: #28a745;  
        border: #E8D426;  
        }  
    </style>  
</head>  
<body>  

    <div class="pt-5">  
        <h1 class="text-center"> CALORIE TRACKER APPLICATION </h1>  
        <div class="container">  
            <div class="row">  
                <div class="col-md-5 mx-auto">  
                    <div class="card card-body">  
                        <form>
                            {% csrf_token %}
                
                            <div class="form-group required">  
                                <label for="email"> Email </label>  
                                <input type="email" class="form-control text-lowercase" id="id_email" name="email">  
                            </div>      

                            <div class="form-group required">  
                                <label class="d-flex flex-row align-items-center" for="password"> Password   
                                <a class="ml-auto border-link small-xl" href="http://127.0.0.1:8000/passwordreset/"> Forget Password? </a> </label>   
                                <input type="password" class="form-control" id="id_password" name="password">  
                            </div>   

                            <div class="form-group pt-1 text-center">  
                                <button class="btn btn-primary btn-block submit" type="submit"> Log In </button>  
                            </div>  

                        </form>  
                        <p class="small-xl pt-3 text-center">  
                            <span class="text-muted"> Not a user? </span>  
                            <a href="http://127.0.0.1:8000/signup/"> Sign up </a>  
                        </p>  

                    </div>  
                </div>  
            </div>  
        </div>  
    </div>  
  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
    
    <script>

        $('.submit').click(function(event) {
            event.preventDefault();
            var email = $("#id_email").val();
            var password = $("#id_password").val();       
            $.ajax({
            url: 'http://127.0.0.1:8000/login/',
            type: 'POST',
            data: {
                email: email,
                password: password,
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                },
                success: function(response) {
                    console.log(response)
                    if (response.status === 'success') {
                        var userType = response.data.user_type;
                        var email = response.data.email;
                        var userId = response.data.user_id;
                        var accessToken = response.access_token;
                        var refreshToken = response.refresh_token;
          
                        // Store in local storage for future use
                        localStorage.setItem('userId', userId);
                        localStorage.setItem('email', email);
                        localStorage.setItem('accessToken', accessToken);
                        localStorage.setItem('refreshToken', refreshToken);

                        if (userType === 'admin') {
                            alert("LOGIN SUCCESSFUL")
                            window.location.href = 'http://127.0.0.1:8000/adminhome/';
                        } else {
                            alert("LOGIN SUCCESSFUL")
                            window.location.href = 'http://127.0.0.1:8000/home/';
                    }
                  } else {
                    console.log(response)
                        alert(response.message)
                        window.location.href = 'http://127.0.0.1:8000/loginpage/';
                    }
                },
                error: function(error) {
                    console.log(error)
                    alert("Invalid Credentials! Please try again")
                    window.location.href = 'http://127.0.0.1:8000/loginpage/';
                }
              });
            });

    </script>
</body>  
</html> 

calorie_tracker_app/accounts/templates/old_userlogin.html
<! DOCTYPE html>  
<html lang="en" >  
<head>  
    <meta charset="UTF-8">  
    <title> Login Page </title>  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">  

    <style>  
        h1 {  
            color: blue;  
            padding-bottom: 2rem;  
            font-weight: bold;  
        }  
        a {  
        color: #333;  
        }  
        a:hover {  
        color: #E8D426;  
        text-decoration: none;  
        }  
        .form-control:focus {  
            color: #000;  
            background-color: #fff;  
            border: 2px solid #E8D426;  
            outline: 0;  
            box-shadow: none;  
        }  
        .btn {  
        
        border: #E8D426;  
        }  
        .btn:hover {  
        background: #28a745;  
        border: #E8D426;  
        }  
    </style>  
</head>  
<body>  

    <div class="pt-5">  
        <h1 class="text-center"> CALORIE TRACKER APPLICATION </h1>  
        <div class="container">  
            <div class="row">  
                <div class="col-md-5 mx-auto">  
                    <div class="card card-body">  
                        <form>
                            {% csrf_token %}
                
                            <div class="form-group required">  
                                <label for="email"> Email </label>  
                                <input type="email" class="form-control text-lowercase" id="id_email" name="email">  
                            </div>      

                            <div class="form-group required">  
                                <label class="d-flex flex-row align-items-center" for="password"> Password   
                                <a class="ml-auto border-link small-xl" href="http://127.0.0.1:8000/celeryresetpassword/"> Forget Password? </a> </label>   
                                <input type="password" class="form-control" id="id_password" name="password">  
                            </div>   

                            <div class="form-group pt-1 text-center">  
                                <button class="btn btn-primary btn-block submit" type="submit"> Log In </button>  
                            </div>  

                        </form>  
                        <p class="small-xl pt-3 text-center">  
                            <span class="text-muted"> Not a user? </span>  
                            <a href="http://127.0.0.1:8000/signup/"> Sign up </a>  
                        </p>  

                    </div>  
                </div>  
            </div>  
        </div>  
    </div>  
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
    
    <script>
        $('.submit').click(function(event){
            event.preventDefault();
            var email = $("#id_email").val();
            var password = $("#id_password").val();
            window.localStorage.setItem("email", email)

            $.ajax({
                url : 'http://127.0.0.1:8000/token/',
                type : "POST",
                data : {
                        email: email,
                        password: password,
                        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                        },
                success: function (Response) { 
                        alert("LOGIN SUCCESSFUL");
                        //console.log(Response)
                        //alert(Response.access)
                        window.localStorage.setItem('refreshToken', Response['refresh']);
                        const refreshToken = localStorage.getItem('refreshToken');
                        //console.log(refreshToken)
                        window.localStorage.setItem('accessToken', Response['access']);
                        const accessToken = localStorage.getItem('accessToken');
                        //console.log(accessToken)
                        window.location.href= "http://127.0.0.1:8000/home/";   
                        },
                error: function(Response){
                            //alert(Response)
                            //console.log(Response)
                            alert(Response.responseJSON.detail);
                            window.location.href= "http://127.0.0.1:8000/userloginpage/";  
                }
         	})
        });
    </script>
</body>  
</html> 

calorie_tracker_app/accounts/templates/password_reset.html
<! DOCTYPE html>  
<html lang="en" >  
<head>  
    <meta charset="UTF-8">  
    <title> Home Page </title>  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">  

    <style>  
        body {  
            background: linear-gradient(to bottom left, white 70%, lightblue);
            font-family: Roboto, sans-serif;
            }
        h1 {  
            color: blue;  
            padding-bottom: 2rem;  
            font-weight: bold;  
        }  
        a {  
        color: #333;  
        }  
        a:hover {  
        color: #E8D426;  
        text-decoration: none;  
        }  
        .form-control:focus {  
            color: #000;  
            background-color: #fff;  
            border: 2px solid #E8D426;  
            outline: 0;  
            box-shadow: none;  
        }  
        .btn {  
        
        border: #E8D426;  
        }  
        .btn:hover {  
        background: #28a745;  
        border: #E8D426;  
        }  
    </style>  
</head> 
<body>  

    <div class="pt-5">  
        <h1 class="text-center"> CALORIE TRACKER APPLICATION </h1>  
    </div>
    <div id="id_div" class="text-center">
        <h3> Password Reset </h3> <br>
        <p>Forgotten your password? Enter your email address below, and we will provide a password rest link. </p>
        <form method =POST>
            {% csrf_token %}
            <input type="email" class="form-control text-lowercase" id="id_email" name="email">  
            <br>
            <button type="submit" class="btn btn-primary reset" >Submit</button>
        </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
    
    <script>

        $('.reset').click(function(event){

            event.preventDefault();
            var email = $("#id_email").val();
            console.log("email")
            $.ajax({
                {% comment %} url : 'http://127.0.0.1:8000/resetpassword/', {% endcomment %}

                url : 'http://127.0.0.1:8000/celeryresetpassword/',
                type : "POST",
                data : {
                        email: email,
                        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                        },
                success: function (response) {
                            window.location.href= "http://127.0.0.1:8000/resetpasswordsent/";  
                        },
                error: function(Response){
                            console.log(Response)
                            if(Response.responseJSON.email){
                                alert(Response.responseJSON.email)
                            }else{
                                alert(Response.responseJSON.message)
                            }
                            //window.location.href= "http://127.0.0.1:8000/users/login/";  
                        }
         	})
        });
    
    </script>
</body>  
</html> 

calorie_tracker_app/accounts/templates/signup.html
<! DOCTYPE html>  
<html lang="en" >  
<head>  
    <meta charset="UTF-8">  
    <title>  Signup Page </title>  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">  

    <style>  

        h1 {  
            color: blue;  
            padding-bottom: 2rem;  
            font-weight: bold;  
        }  
        a {  
        color: #333;  
        }  
        a:hover {  
        color: #E8D426;  
        text-decoration: none;  
        }  
        .form-control:focus {  
            color: #000;  
            background-color: #fff;  
            border: 2px solid #E8D426;  
            outline: 0;  
            box-shadow: none;  
        }  
        .btn {  
        
        border: #E8D426;  
        }  
        .btn:hover {  
        background: #28a745;  
        border: #E8D426;  
        }  
    </style>  
</head>  
<body>  
    <div class="pt-5">  
        <h1 class="text-center"> CALORIE TRACKER APPLICATION  </h1>  
        <div class="container">  
            <div class="row">  
                <div class="col-md-5 mx-auto">  
                    <div class="card card-body">  
                        <form method = "POST" id="signupForm">
                            {% csrf_token %}
            
                
                            <div class="form-group required">  
                                <label for="firstname"> First Name </label>  
                                <input type="firstname" class="form-control" id="id_firstname" name="firstname">  
                            </div> 

                            <div class="form-group required">  
                                <label for="lastname">Last Name</label>  
                                <input type="lastname" class="form-control" id="id_lastname" name="lastname">  
                            </div> 

                            <div class="form-group required">  
                                <label for="email"> Email </label>  
                                <input type="email" class="form-control" id="id_email" name="email">  
                            </div> 

                            <div class="form-group required">  
                                <label class="d-flex flex-row align-items-center" for="password"> Password </label>  
                                <input type="password" class="form-control" id="id_password" name="password">  
                            </div>    

                            <div class="form-group required">  
                                <label class="d-flex flex-row align-items-center" for="password2"> Repeat Password </label>  
                                <input type="password2" class="form-control" id="id_password2" name="password2">  
                            </div>   

                            <div class="form-group required">  
                                 <label class="d-flex flex-row align-items-center" for="is_staff"> User Type</label> 
                                <select name="is_staff" id="id_is_staff">
                                    <option value="">--Please choose an option--</option>
                                    <option value="false">User</option>
                                    <option value="true">Admin</option>
                                </select>
                            </div>  
                            <div class="form-group pt-1">  
                                <input type="submit" class="btn btn-success m-3 p-2 " value = "signup" id="signup"> 
                            </div>  
                        </form>  
                    </div>  
                </div>  
            </div>  
        </div>  
    </div>  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
    <script>
    
        $(document).on('submit', '#signupForm', function(event){

            event.preventDefault();
            var get_firstname = $('#id_firstname').val();
            var get_lastname = $('#id_lastname').val();
            var get_email = $('#id_email').val();
            var get_password = $('#id_password').val();
            var get_password2 = $('#id_password2').val();
            var get_is_staff = $('#id_is_staff').val();
            console.log(get_is_staff)

            $.ajax({
                url : "http://127.0.0.1:8000/create/",
                type : "POST",
                data : {
                        first_name: get_firstname,
                        last_name: get_lastname,
                        email: get_email,
                        is_staff : get_is_staff,
                        password: get_password,
                        password2: get_password2,
                        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                        },                 
            success: function (response) {
                        console.log(response)

                        alert("User registered successfully");
                        window.location.href = "http://127.0.0.1:8000/loginpage/";	           
                    },
            error: function(Response){
                    alert("An user with this email id already exist")
                    window.location.href= "http://127.0.0.1:8000/loginpage/";  
                    }
            
        })
    })
    </script>
</body>  
</html> 