ticket_issuance_system/ticket_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('userandevent.urls')),
    path('ticket/', include('ticketandpayment.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)       
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ticket_issuance_system/userandevent/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views


urlpatterns = [

    #user urls
    path('create/', UserRegister.as_view(),name='user_register'),
    path('list/', UserList.as_view(),name='user_list'),
    path('detail/<int:pk>/', UserDetail.as_view(),name='user_detail'),
    path('update/<int:pk>/', UserUpdate.as_view(),name='user_update'),
    path('delete/<int:pk>/', UserDelete.as_view(),name='user_delete'),

    path('login/', LoginView.as_view(),name='user_login'),
    path('logout/', Logoutview.as_view(),name='user_logout'),
    #path('loginpage/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),

    path('profile/detail/<int:pk>/', ProfileDetail.as_view(),name='profile_detail'),
    path('profile/update/<int:pk>/', ProfileUpdate.as_view(),name='profile_update'),
    path('profile/delete/<int:pk>/', ProfileDelete.as_view(),name='profile_delete'),
    
    path('changepassword/',PasswordChangeView.as_view(), name='password_change'),
    path('resetpassword/',PasswordReset.as_view(),name="request_password_reset"),
    path('passwordreset/<str:encoded_pk>/<str:token>/',ResetPasswordComplete.as_view(),name="reset-password-url"),

    path('passwordchange/',passwordchangepage, name='password_changepage'),
    path('changepassworddone/',passwordchangedonepage, name='password_change_donepage'),
    path('passwordreset/',passwordresetpage, name='password_resetpage'),
    path('resetpasswordsent/',passwordresetsentpage, name='password_reset_completepage'),
    path('resetpassworddone/',passwordresetdonepage, name='password_reset_donepage'),
    path('resetpassword/<str:encoded_pk>/<str:token>/',passwordresetcompletepage,name="reset-password"),
    path('resetpasswordcomplete/',passwordresetcompletepage, name='password_reset_completepage'),

    #event urls
    path('event/list/', EventList.as_view(),name='event_list'),
    path('event/create/', EventCreate.as_view(),name='event_create'),
    path('event/detail/<int:pk>/', EventDetail.as_view(),name='event_detail'),
    path('event/update/<int:pk>/', EventUpdate.as_view(),name='event_update'),
    path('event/delete/<int:pk>/', EventDelete.as_view(),name='event_delete'),
    path('event/setprice/', SetPricetoEvent.as_view(),name='SetPricetoEvent'),
    path('event/book/', BookanEvent.as_view(),name='bookanevent'),
    path('event/listbyuser/', ListEventsBookedByuser.as_view(),name='event_list_user'),
    path('event/listbyevent/', ListBookingbasedonEvent.as_view(),name='event_list'),
    path('event/seat/', EventSeatAvailability.as_view(),name='event_seatavailabilty'),
    path('event/payment/', PrePaymentInfo.as_view(),name='event_payment'),
    path('listingchatrooms/',ListingChatRooms.as_view(), name='listingchatrooms'),

    #template 
    path('user/',userpage, name='userpage'),
    
    path('addeventpage/',addeventpage, name='addeventpage'),
    path('admineventpage/',admineventpage, name='admineventpage'),
    path('eventdetailpage/',eventdetailpage, name='event_detail_page'),
    path('addpriceeventpage/',addpriceeventpage, name='addpriceeventpage'),
    path('loginpage/',loginpage, name='loginpage'),
    path('signup/',signuppage, name='signup'),
    path('ticket/adminlogin/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('',homepage, name='user_homepage'),
    path('adminhome/',adminhomepage, name='admin_homepage'),
    
    path('bookingpage/',bookingpage, name='bookingpage'),
    
    path('payment_success_page/',paymentsuccesspage, name='payment_success_page'),
    path('payment_cancel_page/',paymentcancelpage, name='payment_cancel_page'),

    path('chat/',chatpageforuser, name='chat_page_user'),
    path('chatadmin/<slug:slug>/',chatpageforadmin, name='chat_page_admin'),
    path('adminrooms/',adminchatroompage, name='chat_page_admin'),

    path('profile/',profilepage, name='profile_page'),
    path('profileupdate/',profileupdatepage, name='profile_update_page'),
]

ticket_issuance_system/ticketandpayment/models.py
from django.db import models
from userandevent.models import *
from .mongodb_utils import db
# Create your models here.

class AdminModule(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, related_name='admin_module')
    def __str__(self):
        return str(self.id) + "- " + str(self.user)
    
# mongo database
ticket_collection = db.testingcollection


class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, null=True)
    event_booking = models.ForeignKey(EventBookings, on_delete=models.CASCADE, null=True)
    session_id = models.CharField(max_length=100, null=True, blank=True)
    amount = models.DecimalField(max_digits=6, decimal_places=2)
    created_at = models.DateTimeField(null=True, blank=True, auto_now_add=True)
    updated_date = models.DateField(null=True, blank=True, auto_now=True)
    status = models.IntegerField(default=0)  # 0-Pending,1- Paid, 2- Failed
    
    def __str__(self):
        return str(self.id) + "- " + str(self.user)+ "- " + str(self.event)+ "- " + str(self.status)


class Pricing(models.Model):
    eventpricing_id = models.CharField(max_length=200, default='defaultvalue')
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    price_id = models.CharField(max_length=100, null=True, blank=True)
    unit_amount = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    currency = models.CharField(max_length=10, null=True, blank=True)

    def __str__(self):
        return str(self.id) + '--' + str(self.eventpricing_id) + '--' + str(self.name)+ '--' + str(self.unit_amount)
    

ticket_issuance_system/userandevent/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
#from ticketandpayment.models import Pricing
# Create your models here.


#class UserManager(BaseUserManager):
    # def _create_user(self, email, password, **extra_fields):
    #     if not email:
    #         raise ValueError('The Email field must be set')
    #     email = self.normalize_email(email)
    #     user = self.model(email=email, **extra_fields)
    #     user.set_password(password)
    #     user.save(using=self._db)
    #     return user

    # def create_user(self, email, password=None, **extra_fields):
    #     extra_fields.setdefault('is_admin', False)
    #     extra_fields.setdefault('is_superuser', False)
    #     return self._create_user(email, password, **extra_fields)

    # def create_superuser(self, email, password=None, **extra_fields):
    #     extra_fields.setdefault('is_admin', True)
    #     extra_fields.setdefault('is_superuser', True)
    #     return self._create_user(email, password, **extra_fields)
    

class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True)
    is_admin = models.BooleanField(default=False)


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    #objects = UserManager()

    def __str__(self):
        return str(self.id) + "- " + self.email


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    date_of_birth = models.DateField(null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return str(self.id) + "- " + str(self.user.first_name) + ' ' + str(self.user.last_name)



class Event(models.Model):

    event_name = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(null=True, blank=True, upload_to='images/')
    created_at = models.DateTimeField(null=True, blank=True, auto_now_add=True)
    total_seats = models.IntegerField(default=100)
    event_start_time = models.DateTimeField(null=True, blank=True)
    event_end_time = models.DateTimeField(null=True, blank=True)
    booked_seats = models.JSONField(null=True, blank=True)
    pricing = models.ManyToManyField('ticketandpayment.Pricing', related_name='events')

    def __str__(self):
        return str(self.id) + '--' + str(self.event_name) + '--' + str(self.event_start_time) + '--' + str(self.event_end_time) + '--' + str(self.total_seats) + '--' + str(self.booked_seats)
    

class EventBookings(models.Model):

    user = models.ForeignKey(User, blank=True,on_delete=models.CASCADE, related_name = 'user_eventbooking')
    event = models.ForeignKey(Event, blank=True,on_delete=models.CASCADE, related_name = 'event_booking')
    booking_date = models.DateTimeField(null=True, blank=True, auto_now_add=True)
    seats_booked = models.JSONField(null=True, blank=True)
    created_at = models.DateTimeField(null=True, blank=True, auto_now_add=True)
    updated_at = models.DateTimeField(null=True, blank=True, auto_now=True)

    def __str__(self):
        return str(self.user) + '--' + str(self.id) + '--' + str(self.event) + '--' + str(self.booking_date)+ '--' + str(self.seats_booked)



class Message(models.Model):
    room_name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    sender = models.CharField(max_length=100, null=True, blank=True)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return str(self.room_name) + '--' + str(self.user) +'--' + str(self.sender) + '--' + str(self.message) + '--' + str(self.timestamp)

ticket_issuance_system/userandevent/templates/add_price_event.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Add Price to Event</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <style>

    h1 {  
      color: blue;  
      padding-bottom: 2rem;  
      font-weight: bold;  
    }  
    body {
      font-family: Arial, sans-serif;
      background-color: #f7f7f7;
    }

    .container {
      max-width: 800px;
      margin: 30px auto;
      padding: 20px;
      background-color: #fff;
      border-radius: 10px;
      box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
    }

    .event-image {
      max-width: 100%;
      height: auto;
      border-radius: 10px;
      margin-bottom: 20px;
    }

    .event-title {
      font-size: 24px;
      font-weight: bold;
      margin-bottom: 10px;
    }

    .event-description {
      font-size: 16px;
      margin-bottom: 20px;
    }

    .event-date {
      font-size: 18px;
      margin-bottom: 10px;
    }

    .event-seats {
      font-size: 16px;
      margin-bottom: 20px;
    }

    .event-pricing {
      font-size: 16px;
    }

    .booked-seats {
      font-size: 16px;
    }

    .links {
      display: flex;
      align-items: center;
    }

  </style>
</head>

<body>
    <br>
    <h1 style="color:blue;text-align:center">TICKET ISSUANCE SYSTEM  </h1> 
    <br>
    
    <div class="links">
      <a class="nav-link back text-danger" href="#">Back</a>
    </div>
  <div class="container" id="event-details-container">
  </div>



  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"></script>
<script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>

  <script>
    $('.back').click(function(){
      localStorage.removeItem("event_id");
      window.location.href='http://127.0.0.1:8000/admineventpage/';
    })

</script>
</body>

</html>

ticket_issuance_system/userandevent/templates/addevent.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
   
	<title>addnewevent</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <style>
        body {  
            background: linear-gradient(to bottom left, white 70%, lightblue);
            font-family: Roboto, sans-serif;
              }
        .form-horizontal {
          width: 300px;
          margin: 0 auto;
        }
      
        .form-group {
          margin-bottom: 5px;
        }
      
        .control-label {
          display: block;
          font-weight: bold;
          margin-bottom: 5px;
        }
      
        .form-control {
          width: 100%;
          padding: 8px;
          border-radius: 4px;
          border: 1px solid #ccc;
          box-sizing: border-box;
        }
      
        select.form-control {
          height: 39px;
        }
      
        .btn-container {
          text-align: center;
        }
      
        .btn-container button {
          margin-right: 10px;
        }
      </style>
      
</head>

<body>
	<br> <br>
    <h1 style="color:blue;text-align:center">TICKET ISSUANCE SYSTEM</h1> 
    <h5 style="text-align:center">Add New Event</h5>
    <br>

    <form class="form-horizontal" id="createeventForm" method="POST">
        {% csrf_token %}
      
        <div class="form-group">
          <label class="control-label" for="name"><b>Name</b></label>
          <input type="text" class="form-control" id="id_name" name="name">
        </div>
      
        <div class="form-group">
          <label class="control-label" for="image"><b>Upload Image</b></label>
          <input type="file" id="image" accept="image/png, image/jpeg" class="form-control-file">
        </div>
      
        <div class="form-group">
          <label class="control-label" for="description"><b>Description</b></label>
          <input type="text" class="form-control" id="id_description" name="description">
        </div>
      
        <div class="form-group">
          <label class="control-label" for="starttime"><b>Start Time</b></label>
          <input type="datetime-local" class="form-control" id="id_starttime" name="starttime">
        </div>

        <div class="form-group">
          <label class="control-label" for="endtime"><b>End Time</b></label>
          <input type="datetime-local" class="form-control" id="id_endtime" name="endtime">
        </div>

        <div class="btn-container">
            <button type="submit" class="btn btn-primary" value="createevent" id="createevent">Submit</button>
            <button type="button" class="btn btn-danger" onclick="closeForm()">Close</button>
          </div>
        </form>

  </form>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
  
  
	
	<script>
function getCombinedDateTime(time) {
    var date = $('#id_starttime').val().split('T')[0];
    return date + 'T' + time.split('T')[1];
}


    $(document).on('submit', '#createeventForm', function(event){

        event.preventDefault();
        
        if (document.getElementById("id_name").value.trim() == "") {
            alert("Please enter Name of event!");
            return false;
        }

        if (document.getElementById("id_description").value.trim() == "") {
            alert("Please enter description!");
            return false;
        }
        if (document.getElementById("id_starttime").value.trim() == "") {
            alert("Please enter Start Date and time of the event!");
            return false;
        }
        if (document.getElementById("id_endtime").value.trim() == "") {
          alert("Please enter End Date and time of the event!");
          return false;
      }
      // var startDateTime = getCombinedDateTime($('#id_startdate').val(), $('#id_starttime').val());
      // var endDateTime = getCombinedDateTime($('#id_enddate').val(), $('#id_endtime').val());
      var startDateTime = getCombinedDateTime($('#id_starttime').val() + ':00');
      var endDateTime = getCombinedDateTime($('#id_endtime').val() + ':00');


        var formData = new FormData();
        formData.append('event_name', $('#id_name').val())
        formData.append('description', $('#id_description').val())
        // formData.append('starttime', $('#id_starttime').val())
        // formData.append('endtime', $('#id_endtime').val())
        formData.append('event_start_time', startDateTime);
        formData.append('event_end_time', endDateTime);
        console.log(formData);
        console.log(formData,"---------------------------");
        alert(formData)
        //formData.append('csrfmiddlewaretoken', $('input[name=csrfmiddlewaretoken]').val())
        var imageFile = $('#image')[0].files[0];
        if (imageFile) {
            formData.append('image', imageFile);
        }
        //var csrfmiddlewaretoken = $('input[name=csrfmiddlewaretoken]').val();
        const csrfmiddlewaretoken = getCookie('csrftoken');
        console.log(csrfmiddlewaretoken);
        $.ajax({
            url : "http://127.0.0.1:8000/event/create/",
            headers: {
              'X-CSRFToken': csrfmiddlewaretoken,
            },
            type : "POST",
            data: formData,
            cache: false,
            processData: false,
            contentType: false,
            enctype: 'multipart/form-data',
            success: function (Response) {
                    alert("Event created successfully");
                    window.location.href='http://127.0.0.1:8000/admineventpage/';	           
                    },
            error: function (Response) {
              console.log(Response.data);
              alert(Response);
                    alert("Event not created");
                    window.location.href='http://127.0.0.1:8000/admineventpage/';	           
                    }
         })
    })
    function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.startsWith(name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
    
    function closeForm(){
        window.location.href = "http://127.0.0.1:8000/admineventpage/";	           
    }
	</script>
</body>
</html>

ticket_issuance_system/userandevent/templates/signup.html
<! DOCTYPE html>  
<html lang="en" >  
<head>  
    <meta charset="UTF-8">  
    <title>  Signup Page </title>  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">  

    <style>  

        h1 {  
            color: blue;  
            padding-bottom: 2rem;  
            font-weight: bold;  
        }  
        a {  
        color: #333;  
        }  
        a:hover {  
        color: #E8D426;  
        text-decoration: none;  
        }  
        .form-control:focus {  
            color: #000;  
            background-color: #fff;  
            border: 2px solid #E8D426;  
            outline: 0;  
            box-shadow: none;  
        }  
        .btn {  
        
        border: #E8D426;  
        }  
        .btn:hover {  
        background: #28a745;  
        border: #E8D426;  
        }  
    </style>  
</head>  
<body>  
    <div class="pt-5">  
        <h1 class="text-center"> TICKET ISSUANCE SYSTEM </h1>  
        <div class="container">  
            <div class="row">  
                <div class="col-md-5 mx-auto">  
                    <div class="card card-body">  
                        <form method = "POST" id="signupForm">
                            {% csrf_token %}
            
                
                            <div class="form-group required">  
                                <label for="firstname"> First Name </label>  
                                <input type="firstname" class="form-control" id="id_firstname" name="firstname">  
                            </div> 

                            <div class="form-group required">  
                                <label for="lastname">Last Name</label>  
                                <input type="lastname" class="form-control" id="id_lastname" name="lastname">  
                            </div> 

                            <div class="form-group required">  
                                <label for="email"> Email </label>  
                                <input type="email" class="form-control" id="id_email" name="email">  
                            </div> 

                            <div class="form-group required">  
                                <label class="d-flex flex-row align-items-center" for="password"> Password </label>  
                                <input type="password" class="form-control" id="id_password" name="password">  
                            </div>    

                            <div class="form-group required">  
                                <label class="d-flex flex-row align-items-center" for="password2"> Repeat Password </label>  
                                <input type="password2" class="form-control" id="id_password2" name="password2">  
                            </div>   

                            {% comment %} <div class="form-group required">  
                                 <label class="d-flex flex-row align-items-center" for="is_staff"> User Type</label> 
                                <select name="is_staff" id="id_is_staff">
                                    <option value="">--Please choose an option--</option>
                                    <option value="false">User</option>
                                    <option value="true">Admin</option>
                                </select>
                            </div>   {% endcomment %}
                            <div class="form-group pt-1">  
                                <input type="submit" class="btn btn-success m-3 p-2 " value = "signup" id="signup"> 
                            </div>  
                        </form>  
                    </div>  
                </div>  
            </div>  
        </div>  
    </div>  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
    <script>
    
        $(document).on('submit', '#signupForm', function(event){

            event.preventDefault();
            var get_firstname = $('#id_firstname').val();
            var get_lastname = $('#id_lastname').val();
            var get_email = $('#id_email').val();
            var get_password = $('#id_password').val();
            var get_password2 = $('#id_password2').val();

            $.ajax({
                url : "http://127.0.0.1:8000/create/",
                type : "POST",
                data : {
                        first_name: get_firstname,
                        last_name: get_lastname,
                        email: get_email,
                        // : get_is_staff,
                        password: get_password,
                        password2: get_password2,
                        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                        },                 
            success: function (response) {
                        console.log(response)

                        alert("User registered successfully");
                        window.location.href = "http://127.0.0.1:8000/loginpage/";	           
                    },
            error: function(Response){
                    alert("Invalid Credentials! Please try again")
                    window.location.href= "http://127.0.0.1:8000/signup/";  
                    }
            
        })
    })
    </script>
</body>  
</html> 