taskmgmt/accounts/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt import views as jwt_views
from django.views.generic.base import TemplateView
from .views import *
  
urlpatterns = [

#     path('token/', jwt_views.TokenObtainPairView.as_view(), name ='token_obtain_pair'),
#     path('token/refresh/', jwt_views.TokenRefreshView.as_view(), name ='token_refresh'),
#     path('token/verify/', jwt_views.TokenVerifyView.as_view(), name ='token_verify'),

        path('home/', TemplateView.as_view(template_name="home.html"), name='home'),
        path('login/', views.UserLogin.as_view(),name='login'),
        path('signup/', views.UserRegistration.as_view(), name='signup'),
        path('signout/', views.signout, name='signout'),

        path('userlist/', UserList.as_view(), name='userslist'),
        path('delete/', DeleteUser.as_view(), name='delete'),

      
 ]




      

















    # path('user/partialupdate/<int:pk>/',views.partialupdate_user,name='partialupdate_user'),

    
     

#     path('changepassword/<int:pk>/', ChangePasswordView.as_view(), name='change_password'),



#     path('user/detail/<int:pk>/', UserDetail.as_view(), name='user-detail-view'),
 

taskmgmt/api/urls.py
from django.urls import path
from . import views
from .views import *


urlpatterns = [

    path('task/create/',views.add_task, name='task-create'),
    path('department/create/',views.add_department, name='department-create'),
    path('employee/create/',views.add_employee, name='employee-create'),
    path('assigntask/<int:pk>/',views.assign_task, name='assign-task'),
    path('unassigntask/<int:pk>/',views.unassign_task, name='unassign-task'),
    
    path('task/',views.task_list,name = 'task-list'),
    path('department/',views.department_list,name = 'department-list'),
    path('employee/',views.employee_list,name = 'employee-list'),

    path('task/detail/<int:pk>/',views.task_detail,name='task-detail'),
    path('department/detail/<int:pk>/',views.department_detail, name='department-detail'),
    path('employee/detail/<int:pk>/',views.employee_detail,name='employee-detail'),

    path('task/update/<int:pk>/',views.update_task,name='update-task'),
    path('department/update/<int:pk>/',views.update_department, name='update-department'),
    path('employee/update/<int:pk>/',views.update_employee,name='update-employee'),

    path('task/partialupdate/<int:pk>/',views.partialupdate_task,name='partialupdate-task'),
    path('department/partialupdate/<int:pk>/',views.partialupdate_department, name='partialupdate-department'),
    path('employee/partialupdate/<int:pk>/',views.partialupdate_employee,name='partialupdate-employee'),
    
    path('task/delete/<int:pk>/',views.delete_task,name='delete-task'),
    path('department/delete/<int:pk>/',views.delete_department, name='delete-department'),
    path('employee/delete/<int:pk>/',views.delete_employee,name='delete-employee'),

    path('task/bulkcreate/',views.bulk_create_task,name = 'bulk-create-task'),
    path('department/bulkcreate/',views.bulk_create_department,name = 'bulk-create-department'),
    path('employee/bulkcreate/',views.bulk_create_employee,name = 'bulk-create-employee'),

	path('task/bulkupdate/',views.bulk_update_task,name = 'bulk-update-task'),
    path('department/bulkupdate/',views.bulk_update_department,name = 'bulk-update-department'),
    path('employee/bulkupdate/',views.bulk_update_employee,name = 'bulk-update-employee'),
	
    path('task/bulkcreatemany/',views.bulk_create_task_manytrue,name = 'bulk-create-task-manytrue'), 
]

taskmgmt/taskmgmt/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('api.urls')),
    path('auth/', include('accounts.urls')),
    path('leave/', include('leave_management.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)       
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

taskmgmt/accounts/models.py
from django.db import models

# Create your models here.

taskmgmt/api/models.py
from django.db import models
from django.forms import IntegerField

# Create your models here.

class TaskModel(models.Model):

	task_name= models.CharField(max_length = 100, null = True, blank=True)
	description = models.TextField(null = True, blank=True)
	startdate = models.DateField(null = True, blank=True)
	enddate = models.DateField(null = True, blank=True)
	
	def __str__(self):
	 	return self.task_name

class DepartmentModel(models.Model):

	department = models.CharField(max_length = 100)
    
	def __str__(self):
	    return self.department


class EmployeeModel(models.Model):

    emp_id = models.IntegerField(primary_key=True)
    first_name = models.CharField(max_length = 50, null = True, blank=True)
    last_name = models.CharField(max_length = 50, null = True, blank=True)
    emp_img = models.ImageField(null = True, blank=True)
    contact_num = models.IntegerField(null = True, blank=True)
    level = models.CharField(max_length = 50, null = True, blank=True)
    designation = models.CharField(max_length = 50, null = True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)
    highest_education = models.CharField(max_length=100, null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_joining = models.DateField(null=True, blank=True)
    department = models.ForeignKey(DepartmentModel, null=False, blank=True,
	             on_delete = models.CASCADE,related_name = 'employ_dept')
    tasks = models.ManyToManyField(TaskModel,related_name='employees_assigned',blank=True)
    
	
    def __str__(self):
	    return "%s %s" % (self.first_name, self.last_name)

       

taskmgmt/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.http import JsonResponse, HttpResponse
from rest_framework import status
from rest_framework.exceptions import AuthenticationFailed
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.renderers import TemplateHTMLRenderer, JSONRenderer
from django.contrib.auth import authenticate, login, logout
from .serializers import *
from django.views.generic import View
from django.contrib import messages



####################################################################################################################################################################


#USER REGISTRATION

class UserRegistration(View):

    def get(self, request):
        return render(request, template_name='signup.html')

    def post(self, request):
            first_name = request.POST.get('first_name')
            last_name = request.POST.get('last_name')
            username = request.POST.get('username')
            email = request.POST.get('email')
            password = request.POST.get('password')
            re_password = request.POST.get('re_password')

            print(first_name,last_name,username,email )

            if(password != re_password):
                messages.add_message(request, messages.INFO, 'passwords donot match.')
            else:
                try:
                    User.objects.get(username = request.POST['username'])
                    return render (request,'signup.html', {'error':'Username is already taken!'})
                except User.DoesNotExist:
                    user = User.objects.create_user(first_name=first_name,last_name=last_name,username=username,email=email, password=password)
                    print("success")
                    return redirect('login')


####################################################################################################################################################################


#USER LOGIN

class UserLogin(View):

    def get(self, request):
        return render(request, template_name='login.html')

    def post(self, request):
        user = authenticate(username=request.POST['username'],password = request.POST['password'])
        if user is not None:
            login(request,user)
            return render(request, template_name='home.html')
        else:
            print("error")
            return JsonResponse({"status":"invalid credentials"})
   

####################################################################################################################################################################


#USER LOGOUT 
    
def signout(request):
    
    logout(request)
    return redirect('login')


####################################################################################################################################################################


#RETRIEVE ALL USERS

class UserList(APIView):
    renderer_classes = [JSONRenderer,TemplateHTMLRenderer]
    template_name = 'userlist.html'
    def get(self, request):
        items = User.objects.order_by('id')
        serializer = userSerializer(items, many =True)
        data=serializer.data
        return Response({'data': data})
       
        
####################################################################################################################################################################


#DELETE USER

class DeleteUser(APIView):
        
    def get(self, request):
        
        delete_id = request.GET.get('delete_id')
        User.objects.get(id=delete_id).delete()
        return JsonResponse({"status":"1"})
       

####################################################################################################################################################################





####################################################################################################################################################################




####################################################################################################################################################################

taskmgmt/accounts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %}<title>   </title> {% endblock %}

    <link rel="stylesheet" href="{% static 'style.css' %}">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous"> {% endcomment %}

</head>


<body>
    <center> <h1>TASK MANAGEMENT SYSTEM</h1> </center>
    {% block content %}   
    <br>
    <br>
    {% endblock %}    
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
</body>

</html>

taskmgmt/accounts/templates/home.html
{% extends 'base.html' %}
{% load static %}

	
{% block title %}   
	<title>Homepage</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.css">
    <link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %}
{% block content %}

	<br> <br>
	
	<center> <h1>TASK MANAGEMENT SYSTEM</h1> <br>
	
	<h2> Welcome {{request.user.username}} </h2>
	</center>

	<p style="text-align:right">
		<a class = "btn btn-danger m-3 p-2" href="{% url 'signout' %}">Signout</a>
	</p>

	
	 <div class="text-center">
		<p>
		  <a href="{% url 'userslist' %}">User- List View</a></p><br>
		
		  {% comment %} <a href="{% url 'partialupdate_user' user.id %}">User- Partial Update</a></p><br>
		  <a href="{% url 'delete_user' user.id %}">User- Delete</a></p><br> {% endcomment %}
	  </div> 

	
	<script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>


{% endblock %}  

taskmgmt/accounts/templates/list.html
{% extends 'base.html' %}
{% load static %}

    {% block title %}
    <title>List</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.css">
    <link rel="stylesheet" href="{% static 'style.css' %}">

    {% endblock %}

    {% block content %}
    <p style="text-align:right">
    <a class = "btn btn-danger m-3 p-2" href="{% url 'home' %}">Back Home</a> </p> 
    <center> <h1 class="page-header">TASK MANAGEMENT SYSTEM</h1> </center>
    <p style="text-align:left">
    <a class = "btn btn-success m-3 p-2" href="{% url 'signup' %}">Create new user</a>  </p>

    <div>
      <table class="table" id="usertable">
        <thead>
          <tr>
            
            <th scope="col">sl no.</th>
            <th scope="col">id</th>
            <th scope="col">first_name</th> 
            <th scope="col">last_name</th> 
            <th scope="col">username</th>
            <th scope="col">email</th> 
            <th scope="col">update</th>
            <th scope="col">delete</th>  
    
          </tr>
        </thead>

        <tbody id="tbody">
            
          {% for profile in data %}
            <tr>
              <th scope="row">{{forloop.counter}}</th>
              <td class="id">{{ profile.id }}</td>
              <td>{{ profile.first_name }}</td>
              <td>{{ profile.last_name }}</td> 
              <td>{{ profile.username }}</td>
              <td>{{ profile.email }}</td>
              
              <td> <button data = "{{ profile.id }}" class ="btn btn-sm btn-warning update"> update </button> </td> 
              <td> <button data = "{{ profile.id }}" class ="btn btn-sm btn-danger delete"> delete </button> </td>
            </tr>
          {% endfor %} 

        </tbody>
      </table> 
    </div>
   
    <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
	  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"></script>
	  
    <script>
      $( document ).ready(function() {
        console.log("success");
        $.ajax({
          url : "{% url 'userslist' %}", 
          type : "GET",
          data : {data},
          success:function(response){
           
              console.log("success");
           
            }
          })   
    });
    /delete function
   
    $('.delete').click(function(){

        var confirmation = confirm("are you sure you want to delete this user?");
    
        if (confirmation) {
        var delete_id = $(this).attr('data'); 
        console.log(delete_id);
        data = {
          delete_id : delete_id,
        };

        delthis=this;

        $.ajax({
          url : "{% url 'delete' %}", 
          type : "GET",
          data : data,
          success:function(response){
            if(response.status == 1){
              console.log("data deleted successfully.");
              alert('user deleted successfully.');
              $(delthis).closest("tr").fadeOut();
              }
            }
          })   
            
        }
    })
       

    {% comment %} //view function
    function viewuser(view_id){
        $.ajax({
            url : "{% url 'detailview' %}", 
            type : "GET",
            data : {
                "view_id": view_id,
                },
            success:function(response){
                console.log(response.status)
                $('#message').text(response.status)
                $('#message').addClass("p-2");
                if(response.status == "successful"){
                    $('#message').addClass("bg-success");
                      window.location="{% url 'home' %}";
                  }
                else{
                      $('#message').addClass("bg-danger");
                  }

              }    
        })
      }
          
    //view call
    $('.view').click(function(){
        var view_id = $(this).attr('data')
        console.log(view_id)
        viewuser(view_id)
      })

    //updateobject function
    function updateobject(object){
      var first_name = item.find('.first_name').text()
      var last_name = item.find('.last_name').text()
      var username = item.find('.username').text()
      var email = item.find('.email').text()
      var update_id = object.find('.update').attr('data')
      console.log(first_name, update_id)
    }

    //update call
    $('.update').click(function(){
      var object = $(this).closest('tr')
      updateobject(object)
    }) {% endcomment %}
	  </script>
  </center>
  {% endblock %}

taskmgmt/accounts/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Loginpage</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %} 
{% block content %}
    <center >
    <br>
    <br>
        <h1 class = alert alert-danger>TASK MANAGEMENT SYSTEM</h1> 
    <br>
    <br>

<div class="container border p-4 rounded col-4">
<h1>Login</h1>
<br>

<form method = "POST" action="{% url 'login' %}">
    {% csrf_token %}
    Username
    <input type="text" name="username" />
    <br> <br>
    Password 
    <input type="password" name="password" />
    <br>
    <br>
    <input class ="btn btn-success m-3 p-2 " type="submit" value= "Login" />
    <br>
    <br>
    <div class="text-center">
        <p>Not a user? 
          <a href="{% url 'signup' %}">Sign Up</a></p>
    </div>

</form>
</div>
<center >
{% endblock %}

taskmgmt/accounts/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Signpage</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %} 
{% block content %}
    <br>
    <br>
        <h1 class = text-center alert alert-danger>TASK MANAGEMENT SYSTEM</h1> 
    <br>
    <br>

    <div class="container border p-4 rounded col-4 ">
        <h3 class ="p-3 text-center"> Signup Form </h3> 
        <form method = "POST" action="{% url 'signup' %}" id="signupForm">
                {% csrf_token %}

                <div class="form-group">
                    <label for="first_name">First Name</label>
                    <input type="text" class="form-control" id="id_first_name" name="first_name" placeholder="Enter first name">
                </div>
                
                <div class="form-group">
                    <label for="last_name">Last Name</label>
                    <input type="text" class="form-control" id="id_last_name" name="last_name" placeholder="Enter last name">
                </div>
        
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" class="form-control" id="id_username" name="username" placeholder="Enter username">
                </div>
                
                <div class="form-group">
                    <label for="email">Email address</label>
                    <input type="email" class="form-control" id="id_email" name="email" placeholder="Enter email">
                </div>
                
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="id_password" name="password" placeholder="Password">
                </div>
                
                <div class="form-group">
                    <label for="re_password">Confirm Password</label>
                    <input type="password" class="form-control" id="id_re_password" name="re_password" placeholder="Confirm Password">
                </div>
            
                
                <center> <input type="submit" class="btn btn-success m-3 p-2 " value = "signup" id="signup"> </center>
         
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
    
    <script>
        $(document).on('submit', '#signupForm', function(event){
            event.preventDefault();
            var first_name = $('#id_first_name').val()
            var last_name = $('#id_last_name').val()
            var username = $('#id_username').val()
            var email = $('#id_email').val()
            var password = $('#id_password').val()
            var re_password = $('#id_re_password').val()

            $.ajax({
                url : "{% url 'signup' %}", 
                type : "POST",
                data : {
                    first_name: first_name,
                    last_name: last_name,
                    username: username,
                    email:email,
                    password: password,
                    re_password: re_password
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                },
                success:function(response){
                    console.log(response)
                }
            })
        })
    </script> 
{% endblock %} 

taskmgmt/accounts/templates/update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Signpage</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %} 
{% block content %}
    <br>
    <br>
        <h1 class = text-center alert alert-danger>TASK MANAGEMENT SYSTEM</h1> 
    <br>
    <br>

    <div class="container border p-4 rounded col-4 ">
        <h3 class ="p-3 text-center"> Update Form </h3> 
        <form method = "POST" action="{% url 'update' %}" id="updateForm">
                {% csrf_token %}

                <div class="form-group">
                    <label for="first_name">First Name</label>
                    <input type="text" class="form-control" id="id_first_name" name="first_name" placeholder="Enter first name">
                </div>
                
                <div class="form-group">
                    <label for="last_name">Last Name</label>
                    <input type="text" class="form-control" id="id_last_name" name="last_name" placeholder="Enter last name">
                </div>
        
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" class="form-control" id="id_username" name="username" placeholder="Enter username">
                </div>
                
                <div class="form-group">
                    <label for="email">Email address</label>
                    <input type="email" class="form-control" id="id_email" name="email" placeholder="Enter email">
                </div>
                                
                <center> <input type="submit" class="btn btn-success m-3 p-2 " value = "update" id="update"> </center>
         
        </form>
    </div>

taskmgmt/accounts/templates/userdetail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Detailview</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.css">
    <link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %}

{% block content %}

<center> 
    <br> <br>
    <h1>TASK MANAGEMENT SYSTEM</h1> <br>
    <h1 class="page-header">User Detail</h1> 
    <div>
        <table class="table" id="usertable">
            <thead>
                <tr>
                    <th scope="col">id</th>
                    <th scope="col">first_name</th> 
                    <th scope="col">last_name</th> 
                    <th scope="col">username</th>
                    <th scope="col">email</th> 
                    <th scope="col">update</th>
                    <th scope="col">delete</th>
                </tr>
            </thead>
    
            <tbody>
                <tr>
                    <td>{{ user.id }}</td>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.last_name }}</td>
                    <td>{{ user.username }}</td>
                    <td>{{ user.email }}</td>
                    <td> <button data = "{{ user.id }}" class ="btn btn-warning update"> update </button> </td>
                    <td> <button data = "{{ user.id }}" class ="btn btn-danger delete"> delete </button> </td> 
                </tr>
            <tbody>
        </table>
    </div>


    <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
	<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"></script>
    <script>
        //data table 
		$(document).ready( function () {
            $('#usertable').DataTable();
        } );
    </script>

</center> 

{% endblock %}

taskmgmt/accounts/templates/userlist.html
{% extends 'base.html' %}
{% load static %}

    {% block title %}
    <title>Listview</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.css">
    <link rel="stylesheet" href="{% static 'style.css' %}">

    {% endblock %}

    {% block content %}
    <p style="text-align:right">
    <a class = "btn btn-danger m-3 p-2" href="{% url 'home' %}">Back Home</a> </p> 
    <center> <h1 class="page-header">TASK MANAGEMENT SYSTEM</h1> </center>
    <p style="text-align:left">
    <a class = "btn btn-success m-3 p-2" href="{% url 'signup' %}">Create new user</a>  </p>

    <div>
      <table class="table" id="usertable">
        <thead>
          <tr>
            
            <th scope="col">sl no.</th>
            <th scope="col">id</th>
            <th scope="col">first_name</th> 
            <th scope="col">last_name</th> 
            <th scope="col">username</th>
            <th scope="col">email</th> 
            <th scope="col">update</th>
            <th scope="col">delete</th>  
    
          </tr>
        </thead>

        <tbody id="tbody">
            
          {% for profile in data %}
            <tr>
              <th scope="row">{{forloop.counter}}</th>
              <td class="id">{{ profile.id }}</td>
              <td>{{ profile.first_name }}</td>
              <td>{{ profile.last_name }}</td> 
              <td>{{ profile.username }}</td>
              <td>{{ profile.email }}</td>
              <td> <button data = "{{ profile.id }}" class ="btn btn-sm btn-warning update"> update </button> </td> 
              <td> <button data = "{{ profile.id }}" class ="btn btn-sm btn-danger delete"> delete </button> </td>
            </tr>
          {% endfor %} 

        </tbody> 
      </table>
    </div>
   
    <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
	  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"></script>
	  
    <script>
      
      //retrieve
      $(document).ready(function() {
          $.ajax({
            type : "GET",
            url : "{% url 'userslist' %}", 
            success : function(response){
              $('#usertable').DataTable();   
                console.log(response);
            }
          });
        }); 
      
      
      //delete function
   
        $('.delete').click(function(){

          var confirmation = confirm("are you sure you want to delete this user?");
      
          if (confirmation) {
          var delete_id = $(this).attr('data'); 
          console.log(delete_id);
          data = {
            delete_id : delete_id,
          };

          delthis=this;

          $.ajax({
            url : "{% url 'delete' %}", 
            type : "GET",
            data : data,
            success:function(response){
              if(response.status == 1){
                console.log("user deleted successfully.");
                alert('user deleted successfully.');
                $(delthis).closest("tr").fadeOut();
                }
              }
            })   
              
          }
      })
      
      //update function
        function updateuser(user){
          var first_name = user.find('.first_name').val()
          var last_name = user.find('.last_name').text()
          var username = user.find('.username').text()
          var last_name = user.find('.email').text()
          var update_id = user.find('.update').attr('data')
          console.log(first_name,last_name,update_id)
        }
            $('.update').click(function(){
              var user = $(this).closest('tr');
              var confirmation = confirm("are you sure you want to update this user?");
          
              if (confirmation) {
                updateuser(user);
                console.log("hai");
              
              }
          })

	  </script>
  </center>
  {% endblock %}